name: tong
channels:
- conda-forge
- https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
- https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
- https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
- https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
- https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/
- bioconda
- https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
- defaults
dependencies:
- _libgcc_mutex=0.1=conda_forge
- _openmp_mutex=4.5=2_gnu
- aiodns=3.5.0=py310h06a4308_0
- aiohappyeyeballs=2.6.1=py310h06a4308_0
- aiohttp=3.12.15=py310hb25bd0a_0
- aiosignal=1.4.0=py310h06a4308_0
- alsa-lib=1.2.14=h5eee18b_0
- ansi2html=1.9.1=py310h06a4308_0
- assimp=5.4.3=he621ea3_0
- asttokens=3.0.0=pyhd8ed1ab_1
- async-timeout=5.0.1=py310h06a4308_0
- attr=2.5.2=h39aace5_0
- attrs=25.4.0=py310h06a4308_0
- blas=2.137=openblas
- blas-devel=3.9.0=37_h1ea3ea9_openblas
- blinker=1.9.0=py310h06a4308_0
- blosc=1.21.6=he440d0b_1
- bottleneck=1.4.2=py310ha9d4c09_0
- brotli-python=1.0.9=py310h6a678d5_9
- brotlicffi=1.0.9.2=py310h6a678d5_1
- bzip2=1.0.8=hda65f42_8
- c-ares=1.34.5=hef5626c_0
- ca-certificates=2025.10.5=hbd8a1cb_0
- cairo=1.18.4=h44eff21_0
- certifi=2025.10.5=py310h06a4308_0
- cffi=2.0.0=py310h4eded50_0
- charset-normalizer=3.3.2=pyhd3eb1b0_0
- cli11=2.1.2=h295c915_0
- click=8.2.1=py310h06a4308_0
- comm=0.2.3=pyhe01879c_0
- contourpy=1.3.1=py310hdb19cb5_0
- cycler=0.11.0=pyhd3eb1b0_0
- cyrus-sasl=2.1.28=h1110e0f_3
- dash=2.14.2=py310h06a4308_0
- dbus=1.16.2=h5bd4931_0
- debugpy=1.8.17=py310h25320af_0
- decorator=5.2.1=pyhd8ed1ab_0
- double-conversion=3.3.1=h6a678d5_0
- embree=4.4.0=h5fbf336_0
- exceptiongroup=1.3.0=pyhd8ed1ab_0
- executing=2.2.1=pyhd8ed1ab_0
- expat=2.7.1=h6a678d5_0
- flask=3.0.3=py310h06a4308_0
- flask-compress=1.17=py310h06a4308_0
- fmt=11.2.0=hca5f364_0
- font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
- font-ttf-inconsolata=2.001=hcb22688_0
- font-ttf-source-code-pro=2.030=hd3eb1b0_0
- font-ttf-ubuntu=0.83=h8b1ccd4_0
- fontconfig=2.15.0=h7e30c49_1
- fonts-anaconda=1=h8fa9717_0
- fonts-conda-ecosystem=1=hd3eb1b0_0
- fonttools=4.60.1=py310hee96239_0
- freetype=2.14.1=ha770c72_0
- frozenlist=1.8.0=py310hbdd6827_0
- gettext=0.25.1=h3f43e3d_1
- gettext-tools=0.25.1=h3f43e3d_1
- gl2ps=1.4.2=h70c0345_1
- glew=2.2.0=hcfb9eae_1
- glfw=3.4=h7389608_0
- glib=2.86.0=hbcf1ec1_1
- glib-tools=2.86.0=hf516916_1
- graphite2=1.3.14=h295c915_1
- gst-plugins-base=1.24.11=h651a532_0
- gstreamer=1.24.11=hc37bda9_0
- harfbuzz=12.1.0=h15599e2_0
- hdf4=4.2.15=h2a13503_7
- hdf5=1.14.6=nompi_h6e4c0c1_103
- icu=75.1=he02047a_0
- idna=3.7=py310h06a4308_0
- importlib-metadata=8.5.0=py310h06a4308_0
- ipykernel=7.0.1=pyha191276_0
- ipympl=0.9.7=py310h06a4308_0
- ipython=8.37.0=pyh8f84b5b_0
- ipywidgets=8.1.7=py310h06a4308_0
- itsdangerous=2.2.0=py310h06a4308_0
- jedi=0.19.2=pyhd8ed1ab_1
- jinja2=3.1.6=py310h06a4308_0
- jsoncpp=1.9.6=hfbf14b3_0
- jupyter_client=8.6.3=pyhd8ed1ab_1
- jupyter_core=5.9.1=pyhc90fa1f_0
- jupyterlab_widgets=3.0.15=py310h06a4308_0
- kiwisolver=1.4.8=py310h6a678d5_0
- krb5=1.21.3=h723845a_4
- lame=3.100=h7b6447c_0
- lcms2=2.17=h717163a_0
- ld_impl_linux-64=2.44=h1aa0949_4
- lerc=4.0.0=h6a678d5_0
- libaec=1.1.4=h3f801dc_0
- libasprintf=0.25.1=h3f43e3d_1
- libasprintf-devel=0.25.1=h3f43e3d_1
- libblas=3.9.0=37_h4a7cf45_openblas
- libcap=2.76=h0b2e76d_0
- libcblas=3.9.0=37_h0358290_openblas
- libclang-cpp21.1=21.1.4=default_h99862b1_0
- libclang13=21.1.4=default_h746c552_0
- libcups=2.3.3=hb8b1518_5
- libcurl=8.15.0=hc1efc7f_0
- libdeflate=1.24=h86f0d12_0
- libdrm=2.4.125=hb03c661_1
- libedit=3.1.20230828=h5eee18b_0
- libegl=1.7.0=h5eee18b_2
- libev=4.33=h7f8727e_1
- libevent=2.1.12=hdbd6064_1
- libexpat=2.7.1=hecca717_0
- libffi=3.5.2=h9ec8514_0
- libflac=1.4.3=h59595ed_0
- libfreetype=2.14.1=ha770c72_0
- libfreetype6=2.14.1=h73754d4_0
- libgcc=15.2.0=h767d61c_7
- libgcc-ng=15.2.0=h69a702a_7
- libgcrypt-lib=1.11.1=hb9d3cd8_0
- libgettextpo=0.25.1=h3f43e3d_1
- libgettextpo-devel=0.25.1=h3f43e3d_1
- libgfortran=15.2.0=h69a702a_7
- libgfortran-ng=15.2.0=h69a702a_7
- libgfortran5=15.2.0=hcd61629_7
- libgl=1.7.0=h5eee18b_2
- libglib=2.86.0=h32235b2_1
- libglu=9.0.3=h60c0c69_1
- libglvnd=1.7.0=h5eee18b_2
- libglx=1.7.0=h5eee18b_2
- libgomp=15.2.0=h767d61c_7
- libgpg-error=1.55=h3f2d84a_0
- libiconv=1.18=h3b78370_2
- libjpeg-turbo=3.1.1=hb25bd0a_0
- libkrb5=1.21.3=h520c7b4_4
- liblapack=3.9.0=37_h47877c9_openblas
- liblapacke=3.9.0=37_h6ae95b6_openblas
- libllvm21=21.1.4=hf7376ad_0
- liblzf=3.6=hb9d3cd8_3
- liblzma=5.8.1=hb9d3cd8_2
- libnetcdf=4.9.3=nompi_h11f7409_103
- libnghttp2=1.57.0=h2d74bed_0
- libnsl=2.0.1=hb9d3cd8_1
- libogg=1.3.5=h27cfd23_1
- libopenblas=0.3.30=pthreads_h94d23a6_2
- libopengl=1.7.0=h5eee18b_2
- libopenjpeg=2.5.4=hee96239_0
- libopus=1.5.2=hd0c01bc_0
- libpciaccess=0.18=h5eee18b_0
- libpng=1.6.50=h2ed474d_0
- libpq=18.0=h3675c94_0
- libsndfile=1.2.2=hc60ed4a_1
- libsodium=1.0.20=heac8642_0
- libsqlite=3.50.4=h0c1763c_0
- libssh2=1.11.1=h251f7ec_0
- libstdcxx=15.2.0=h8f9b012_7
- libstdcxx-ng=15.2.0=h4852527_7
- libsystemd0=257.9=h996ca69_0
- libtheora=1.1.1=h7f8727e_3
- libtiff=4.7.1=h8261f1e_0
- libuuid=2.41.2=he9a06e4_0
- libuv=1.48.0=h5eee18b_0
- libvorbis=1.3.7=h7b6447c_0
- libvulkan-loader=1.4.328.1=h5279c79_0
- libwebp-base=1.6.0=hd42ef1d_0
- libxcb=1.17.0=h9b100fa_0
- libxcrypt=4.4.36=hd590300_1
- libxkbcommon=1.12.2=hca5e8e5_0
- libxml2=2.15.1=h26afc86_0
- libxml2-16=2.15.1=ha9997c6_0
- libzip=1.11.2=h6991a6a_0
- libzlib=1.3.1=hb9d3cd8_2
- lmdb=0.9.31=hb25bd0a_0
- loguru=0.7.2=py310h06a4308_1
- lz4-c=1.10.0=h5888daf_1
- markupsafe=3.0.2=py310h5eee18b_0
- matplotlib=3.10.6=py310h06a4308_0
- matplotlib-base=3.10.6=py310h71dd3da_0
- matplotlib-inline=0.2.1=pyhd8ed1ab_0
- mpg123=1.32.9=hc50e24c_0
- msgpack-python=1.1.1=py310h6a678d5_0
- multidict=6.7.0=py310hee96239_0
- narwhals=2.7.0=py310h06a4308_0
- ncurses=6.5=h2d0b736_3
- nest-asyncio=1.6.0=py310h06a4308_0
- nlohmann_json=3.11.2=h6a678d5_0
- nspr=4.37=h8459abe_0
- nss=3.117=h3135ca0_0
- numexpr=2.11.0=py310hccd6f0b_1
- numpy=2.2.6=py310hefbff90_0
- open3d=0.19.0=py310h757a272_6
- openblas=0.3.30=pthreads_h6ec200e_2
- openjpeg=2.5.4=h4e0627c_0
- openldap=2.6.10=he9288cc_1
- openssl=3.5.4=h26f9b46_0
- packaging=25.0=py310h06a4308_1
- pandas=2.3.3=py310h505adc9_0
- parso=0.8.5=pyhcf101f3_0
- pcre2=10.46=hf426167_0
- pexpect=4.9.0=pyhd8ed1ab_1
- pickleshare=0.7.5=pyhd8ed1ab_1004
- pillow=11.3.0=py310h6557065_3
- pip=25.2=pyh8b19718_0
- pixman=0.46.4=h7934f7d_0
- platformdirs=4.5.0=pyhcf101f3_0
- plotly=6.3.0=py310he3bba80_0
- ply=3.11=py310h06a4308_0
- proj=9.7.0=hb72c0af_0
- prompt-toolkit=3.0.52=pyha770c72_0
- propcache=0.3.1=py310h5eee18b_0
- psutil=7.1.0=py310h7c4b9e2_0
- pthread-stubs=0.3=h0ce48e5_1
- ptyprocess=0.7.0=pyhd8ed1ab_1
- pugixml=1.15=h3f63f65_0
- pulseaudio-client=17.0=h9a8bead_2
- pure_eval=0.2.3=pyhd8ed1ab_1
- pybind11-abi=4=hd3eb1b0_1
- pycares=4.10.0=py310ha137689_0
- pycparser=2.23=py310h06a4308_0
- pygments=2.19.2=pyhd8ed1ab_0
- pyparsing=3.2.0=py310h06a4308_0
- pyqt=5.15.10=py310h6a678d5_1
- pyqt5-sip=12.13.0=py310h5eee18b_1
- pysocks=1.7.1=py310h06a4308_0
- python=3.10.19=h3c07f61_2_cpython
- python-dateutil=2.9.0post0=py310h06a4308_2
- python-tzdata=2025.2=pyhd3eb1b0_0
- python_abi=3.10=8_cp310
- pytz=2025.2=py310h06a4308_0
- pyzmq=27.1.0=py310h4f33d48_0
- qhull=2020.2=hdb19cb5_2
- qt-main=5.15.15=h3c3fd16_6
- qt6-main=6.9.3=h5c1c036_1
- readline=8.2=h8c095d6_2
- requests=2.32.5=py310h06a4308_0
- retrying=1.3.3=pyhd3eb1b0_2
- scipy=1.15.3=py310ha592af2_1
- setuptools=80.9.0=pyhff2d567_0
- sip=6.7.12=py310h6a678d5_1
- six=1.17.0=py310h06a4308_0
- snappy=1.2.1=h6a678d5_0
- sqlite=3.50.2=hb25bd0a_1
- stack_data=0.6.3=pyhd8ed1ab_1
- tbb=2022.0.0=hdb19cb5_0
- tinyobjloader=1.0.7=h59595ed_2
- tk=8.6.13=noxft_hd72426e_102
- tomli=2.2.1=py310h06a4308_0
- tornado=6.5.1=py310h5eee18b_0
- traitlets=5.14.3=pyhd8ed1ab_1
- typing-extensions=4.15.0=py310h06a4308_0
- typing_extensions=4.15.0=py310h06a4308_0
- tzdata=2025b=h78e105d_0
- urllib3=2.5.0=py310h06a4308_0
- utfcpp=3.2.1=h06a4308_0
- uvloop=0.21.0=py310h5eee18b_0
- vtk-base=9.5.1=py310h991dc19_7
- wayland=1.24.0=hdac8c69_0
- wcwidth=0.2.14=pyhd8ed1ab_0
- werkzeug=3.0.6=py310h06a4308_0
- wheel=0.45.1=pyhd8ed1ab_1
- widgetsnbextension=4.0.14=py310h06a4308_0
- wslink=2.5.0=pyhd8ed1ab_0
- xcb-util=0.4.1=h5eee18b_2
- xcb-util-cursor=0.1.5=h5eee18b_0
- xcb-util-image=0.4.0=h5eee18b_2
- xcb-util-keysyms=0.4.1=h5eee18b_0
- xcb-util-renderutil=0.3.10=h5eee18b_0
- xcb-util-wm=0.4.2=h5eee18b_0
- xkeyboard-config=2.44=h5eee18b_0
- xorg-libice=1.1.2=h9b100fa_0
- xorg-libsm=1.2.6=he73a12e_0
- xorg-libx11=1.8.12=h9b100fa_1
- xorg-libxau=1.0.12=h9b100fa_0
- xorg-libxcomposite=0.4.6=h9b100fa_2
- xorg-libxcursor=1.2.3=h9b100fa_0
- xorg-libxdamage=1.1.6=h9b100fa_0
- xorg-libxdmcp=1.1.5=h9b100fa_0
- xorg-libxext=1.3.6=h9b100fa_0
- xorg-libxfixes=6.0.2=hb03c661_0
- xorg-libxi=1.8.2=h9b100fa_0
- xorg-libxinerama=1.1.5=h50385e7_1
- xorg-libxrandr=1.5.4=h9b100fa_0
- xorg-libxrender=0.9.12=h9b100fa_0
- xorg-libxshmfence=1.3.3=h9b100fa_0
- xorg-libxtst=1.2.5=h9b100fa_3
- xorg-libxxf86vm=1.1.6=h9b100fa_0
- xorg-xorgproto=2024.1=h5eee18b_1
- yarl=1.18.0=py310h5eee18b_0
- zeromq=4.3.5=hb0a5e54_1
- zipp=3.21.0=py310h06a4308_0
- zlib=1.3.1=hb9d3cd8_2
- zstandard=0.24.0=py310h3d778a8_0
- zstd=1.5.7=hb8e6e7a_2
prefix: /opt/tong/bin/miniconda3/envs/tong
